# here we are using almalinux image free image: it is exactly same as redhat/ubi9 image but completely free gives logs
FROM almalinux:9
RUN dnf install nginx -y
CMD ["nginx", "-g" ,"dsemon -offf;"]
LABEL COURSE="DOCKER" \
      TRAINER="Vineeth" \
      DURATION="10HRS"
